'use client'
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import { poppins } from "@/utils/fonts";
import useCookieStore from "@/store/useCookieStore";
import { useEffect } from "react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const watchCookies = useCookieStore((state) => state.watchCookies);
  
  useEffect(() => {
    watchCookies();
  }, [watchCookies]);

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Toaster />
      
        <Navbar />
        {children}
      </body>
    </html>
  );
}
